listening-port=3478
tls-listening-port=5349
min-port=55000
max-port=60000
fingerprint
lt-cred-mech
user=demo:demopass
realm=remote-desktop.local
no-loopback-peers
no-multicast-peers
stale-nonce=600
verbose
